image: node:19

stages:
    - build
    - test
    - sonar

cache:
    paths:
        - node_modules/

variables:
  # to be defined in specific pipeline
  coverage_path: "$CI_PROJECT_DIR/coverage/lcov.info"


build:
    stage: build
    script:
        - npm ci
        - npm run build
    tags:
        - nlp-runner

test:
    stage: test
    script:
        - echo $coverage_path
        - npm ci
        - npx jest --coverage --coverageDirectory=$coverage_path
    tags:
        - nlp-runner
    artifacts:
        paths:
            - $coverage_path


sonar:
    stage: sonar
    allow_failure: true
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: [ "" ]
    script:
        - echo $coverage_path
        - sonar-scanner -h
        - sonar-scanner -D sonar.projectKey=$SONAR_PROJECT_KEY
                        -D sonar.sources=.
                        -D sonar.host.url=$SONAR_URL
                        -D sonar.login=$SONAR_TOKEN
                        -D sonar.sources='.'
                        -D sonar.exclusions='**/*.spec.ts,**/*.test.ts'
                        -D sonar.javascript.lcov.reportPaths=$coverage_path
    tags:
        - nlp-runner

