include:
  - project: "nlp/team/ci-templates"
    file: "node-js/.lint.yaml"
  - project: "nlp/team/ci-templates"
    file: "node-js/.build.yaml"
  - project: "nlp/team/ci-templates"
    file: "node-js/.test.yaml"
  - project: "nlp/team/ci-templates"
    file: "node-js/.sonar.yaml"
  - project: "nlp/team/ci-templates"
    file: "node-js/.docker-build.yaml"
  - project: "nlp/team/ci-templates"
    file: "node-js/.publish-k8s.yaml"

default:
  interruptible: true

cache:
  # following paths are automatically cached and available for subsequent jobs
  paths:
    - node_modules/

variables:
  coverage_dir: "$CI_PROJECT_DIR/coverage"
  coverage_path: "$coverage_dir/lcov.info"
  REGISTRY_IMAGE: davos.fhgr.ch/nlp/orbis2/$CI_PROJECT_NAME
  KUBE_NAMESPACE: orbis2
  VERSION: "$CI_COMMIT_TAG"
  DOCKERFILEPATH: dockerfile

stages:
  - lint
  - build
  - test
  - sonar
  - dockerbuild
  - publish-k8s
